/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 719a9b9d5c3e31201a2300bf810f75e5)
interface __BaseEnv_Env {
	SALES_ARCHIVE: R2Bucket;
	DB: D1Database;
	STOCKHUB: Fetcher /* stockhub-staging */ | Fetcher /* stockhub */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface StagingEnv {
		SALES_ARCHIVE: R2Bucket;
		DB: D1Database;
		STOCKHUB: Fetcher /* stockhub-staging */;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
